development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: log/production.sqlite3 # dirty workaround for "cap depoy" refresh db directories...
  pool: 5
  timeout: 5000
